language: java
jdk: openjdk8
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: gAcu/8DC2Ku4E1J6WxHpD5OqEBHPsZFYonGbeKFjX2FqKRDG80/TZN6XyNxBWuVGJcuwxLcJ6PWLuj6v6j3Jdmwxsv14xneE8js4PMnjtsNexsfsISg0IyvEageuwmarF15kHwrFY4lgoLatxOQEEBYKXz4kzNYpv+CKKV6eNcQ=
  - secure: lo5+ZJsZEFe+QdCOn1LPKKcCDa4dcawKwPjJCkHOsfdpfr+Z+8FmKuoBDqrkGx/idT1pGDsWaY9hBZHhy+2YHVG8xjxIihBsxct02mFuVm+03Bam6NZW/tLxWEacceYrFg/j+B6zke0ERwwhl8PVp2XoQxa4ecQ6yXzgSN5uHOc=
  - secure: QXwC062UnHW6CDqGxeC6f+uY2iBF28dQa9+jVhm7U9LbrQWAWx9WF6YoO8bP31opscEOVbr96PEwFHNIkSPqjWw9IQN89iTRn/fJVYREONQuYRiBJGYM6egaWJ/21NPrgkCQrmIYlmqtIIbi380wu9oPzSCasqk1Wj0YTtBlLsY=
  - secure: UP8sYxhtU73zHAt0pAQWzmmIyJutxIAYFVfRYZ+sRUO9II75inFdjNX3zOAOLscAwwTwo1DwmC11T0AoYSAzwqSAKpxa9lkpMtSglzr0nyJd5N5A8Cu32JNz4pt/MhnZuj/tlAQFPfEiuwQWDcIpXOtvfkyzVY3lIgAMTQeqhUo=
  - secure: LV2tgBy/J8pWYhCpnt1MWpimH9b9L2pnqrk3BQ7EoGmkkMO4a1B5X8RMpHeXYtzwqkZKqgMES7NINluN6tTlVwb6+wKmulQvOF7SiDB97tfdw5725ckyxyzJDrla3kzUIwX+GyUSrFJRhmurB9h+1PkI3PihWM5cIkZEWK4UKPY=
  - secure: S2AileKaFBmT0NhXhdYwLQX+a8Evoh8oUKcA4OX1gMVRbdfFzHHLXuDShrARKOJT41v8VB1xPTYqd2aPfk4nndi0FE3fuLgubPd7dnOIpWCLv8+5BKsRxk82BGvtaK0dbAasBl142NLZK1GYjAsbQSV8FowPA372Ql7Qm0KXcc4=
