language: java
jdk: openjdk8
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: hi0Hk8aRaJ+bj7zriNuu1t6q6jPdXizghIESDgOnBDlfRafuSezNXjGS3k4zDkRiuWc96FP2pWziw7UeAH1XwLI23bVXeLBMDNICpZbdvuhyg6+d70ahu9RP39EN9oQB2474Qds7PNdZZubQgZfcC2ymeLEqnoLPk840LRl1Ykc=
  - secure: suEchkITudA8ZfRnu3Lb20MYrO9ORKJG6ubQoDmGp4icMclNtNVOS3+cShnSighlyPqhZ1ASiDEEYyfOPZvbAjHNaa08RDMuZdTkCKyPfNpeG2JcNMxJSvRZiFHB26+N+KhOkPOAvxHDvLsHpKw6/j+k90Pt3SWRT+PmqZgEGzM=
  - secure: UToQcqnbY741EI5/rR3YjKelI3avnwzVbytAXkq/rDGLUuxMTXyZvHEPgJBrNXTCP3RMoCw9Pml/B7l11vS1hhAz0YUYrkNhE0wM3nyIU94NCvjbp8kLJt7H2yhpCk6uffRuKijcQpGFqBZazm7ShUXgtcP8aDZ7Zr8UFMrKjV0=
  - secure: NOv7/lmUAYGZXZuegeuPu6f4jvUcBLvJme7mKuzoNwALUBoXUdvxBCTM/Gi7WcSckXLMYow1LnZTTIcZC/1olZJfpfzFi0/3Jg2aVfH/6jNG87uJpr93GgXnw6k6jyAFSN8kB4TMByL2swuDzGGZZ/RXeg0XUDmUyjVTaI8HGPw=
  - secure: TPeUxPe03Rpmh/WBrabwjOhzuH9F7+ZqRO7cNS995Zt+v+s9vXQ6rVhSL98XkSPn+1nF01aI/HHEQ2sJNpkpAXNSBfluDo/0818L9LFnsi3NVN2r9b4++wJJSzN5qWzisk/tT/DeEiOx1eJNtMzMOf97ouMmU5dHD7T/3kRyaVo=
  - secure: mol6p/NuEczzrX/ig1CDV2mPOdDqAtjW+M9PA69ufC2QzLf2zJTlKjxzddTAk83QZN2APGOrxAQEgkXiVXnoDxqQqIlnytsB+/6IjfksOktzaYvh2m7vgSdDtclMN7ANf3FTyVCznBexEpPasrW8SYpR2NR0agogBH1zrh9KndI=
