language: java
jdk: openjdk8
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: qv9GVeHffQ1IP8sMpKGUzuOF7hiKpouzgmXQ2C9+WPkuerbuWdZpH7fbPxql+26WN2VT3dj2DdgqN0pdfDcKxqopy79S9aHNp29C5hZsRY5rc3hWby3AgGTV277BcqAW4JtheNFWJ+rQzteXWumWZOTHh5OQfNiPPIr4EkILEos=
  - secure: O6uwRVl2monRfTsw9CEQXafXnw2eJJAgrfXPYxmz3ANzOV6aV0EW/R8qgNXupuNTtGtuDhu8AvqQwKvZWmIX97bx2fsl3N3tjPEl76VUsKzTSaLwVm4+alLgA+/3W0E1rSFHk/T3SIt4n7mkB/ObYlfCBTTOSLgkckCI91+zkkU=
  - secure: iaoqSSpwDNQQHetnvJdT6bVI5mnEMNeZjjP2cajqfYaGFOjIOWpkkIWpKZ64OBeTV7vctH6mm7hddzOc55O/4TGjOM3VDlGFkuYC/7ZY4GcDNPRrYno5jn0r0Atxs1oGQyh8bcMseBXYMaBL0QbBC0vNqYGkvRcDXmzcR81+cf8=
  - secure: ZXn0LOpDzuv1hUnyK0OPtfPxOmcnAw3kA/PRw55TtqX7xxZAb0F6lObrugUe8GtCS8jEMWwtuJNkY44DHLaULRg96Yezr2Ps5r54+/vvQWxGkecdoFREG4ucj7PKck1DEbfq1r4/Z15zb8IZAeRe2BBKaocmarC9wbVFxBotQbc=
  - secure: J3dOsaTLM6oNeSZFWg62Km1pPGhNRptGpB0CNGkAutlTF2jADpennrx+kQhKvOS8bmCi86MHjJ/tVW5ha0Q002pzJ7JrDjTsBXbUPzWiuy9xfwvnAhLmzyASv6DkcwwcvYKYGP2OoAkzRTmJjstwJyUjbWHn/VdzSKXWPNYDwAE=
  - secure: cjIHvpHHz+Hrwh8lNJVEAaSONxBbFN2pRe6Kngm21vTIN77qv1HnCn/I/GpDN4/YMg7k1ca3y38Cj2CudS6p5t+pT+beaJOLpHk3MY+aP5K4JOa9tnMe+0vLZ/xZapjkCbv8qtb6ngKP2aAgN3vkLm+1/0GHN0120kXfNP4v4Fo=
